---
dependency:
  name: galaxy
driver:
  name: docker
lint: ansible-lint -v
platforms:
  - name: centos_instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: ubuntu_instance
    image: docker.io/pycontribs/ubuntu:sysd
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
