---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: fedora37
    image: quay.io/fedora/fedora:37
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
